>Aptamer|38,103|bound
((((((((((........(((((....)))))..(((((...........)))))))))))))))
NNNNNNNCCUAAAACAUACCAGAGAAAUCUGGAGAGGUGAAGAAUACGACCACCUAGGNNNNNNN
>Aptamer|50,103|unbound
......(((((....)))))..(((((...........)))))..........
AACAUACCAGAGAAAUCUGGAGAGGUGAAGAAUACGACCACCUAGGNNNNNNN
>Access_constraint|50,56
AACAUA
>Hairpin|15,32|unbound
(((((((...)))))))
>Hairpin|0,17|bound
(((((((...)))))))
>Restriction_site|0,10
AUGAGUAUGU
>Context_front|-45,0
.............................................
AAGCUAUACCAAGCAUACAAUCAACUCCAAGCUAGAUCUCUUAAG
>Context_back|103,148
.............................................
AUCUAGCGCUGGUACCAUCCCAUUUAACUGUAAGAAGAAUUGCAC
